/**
 * Строки гида, которые живут в коде. Всё остальное (описания шагов, кнопки
 * скачивания, блок «Если подписка не добавилась») приходит из app-config
 * владельца проекта.
 */
export const guideText = {
  ru: {
    pageTitle: 'Установка',
    inviteExpired: 'Срок действия ссылки истёк. Попросите отправить новую.',
    inviteInvalid: 'Ссылка недействительна. Проверьте, что она скопирована целиком.',
    inviteNoSubscription: 'У этой подписки нет активного доступа.',
    inviteSubscriptionExpired: 'Подписка закончилась. Продлите её в личном кабинете.',
    inviteUnavailable: 'Не удалось подготовить подключение. Попробуйте ещё раз через минуту.',
    configError: 'Не удалось загрузить конфиг приложений',
    noSubscription: 'Подписка не найдена. Сначала оформите тариф.',
    encryptedLoading: 'Готовим защищённую ссылку…',
    encryptedError: 'Не удалось подготовить защищённую ссылку. Попробуйте ещё раз.',

    stepShort: ['Установка', 'Подписка', 'Включение'],
    stepOf: (n: number, total: number) => `Шаг ${n} из ${total}`,
    stepLabel: (n: number) => `Шаг ${n}`,
    stepDone: 'сделано',
    doneShort: 'Готово',
    installTitle: (app: string) => `Установите ${app}`,
    addTitle: 'Добавьте подписку',
    usageTitle: 'Включите VPN',
    alreadyInstalled: 'Уже установлено — дальше',
    installedNext: 'Установил — дальше',
    addSubscription: 'Добавить подписку',
    tryAgain: 'Нажать ещё раз',
    notAdded: 'Подписка не появилась?',
    noticeInstalled: 'Приложение установлено',
    notInstalled: 'Ещё нет',
    noticeAdded: 'Подписка добавлена',
    notAddedShort: 'Не появилась?',
    noOpenLead: (app: string) => `${app} не открылся?`,
    noOpenTip: 'Возможно, приложение ещё не установлено. Видео и ручной способ —',
    connected: 'VPN включился',
    markedDone: 'Сделано',
    more: 'Подробнее',
    less: 'Свернуть',

    helpTitle: 'Что-то не получилось?',
    helpFallbackTitle: 'Если подписка не добавилась',
    helpHowTo: 'Как добавить подписку',
    copyLink: 'Скопировать ссылку подписки',
    copyLinkHint: 'Добавить вручную',
    copied: 'Скопировано',
    support: 'Написать в поддержку',

    change: 'Изменить',
    pickerTitle: 'Какое у вас устройство?',
    pickerApp: 'Приложение',
    recommended: 'Рекомендуем',
    pickerDone: 'Готово',
    close: 'Закрыть',

    finaleTitle: 'Готово! VPN подключён 🎉',
    finaleTitleShort: 'Готово! 🎉',
    finaleText: (brand: string, app: string) =>
      `${brand ? `Подписка ${brand}` : 'Подписка'} добавлена в ${app}. Включать и выключать VPN — большой кнопкой в приложении.`,
    anotherDevice: 'Подключить ещё устройство',
    showSteps: 'Показать шаги',
    toHome: 'На главную',

    illAdd: '+ Подписка',
    illAdded: 'подписка добавлена',
    illOff: 'Выключено',
    illOn: 'Подключено',
  },
  en: {
    pageTitle: 'Setup',
    inviteExpired: 'This link has expired. Ask for a new one.',
    inviteInvalid: 'This link is not valid. Make sure it was copied in full.',
    inviteNoSubscription: 'This subscription has no active access.',
    inviteSubscriptionExpired: 'The subscription has ended. Renew it in the account.',
    inviteUnavailable: 'Could not prepare the connection. Please try again in a minute.',
    configError: 'Could not load app config',
    noSubscription: 'Subscription not found. Purchase a plan first.',
    encryptedLoading: 'Preparing secure link…',
    encryptedError: 'Could not prepare the secure link. Please try again.',

    stepShort: ['Install', 'Subscription', 'Connect'],
    stepOf: (n: number, total: number) => `Step ${n} of ${total}`,
    stepLabel: (n: number) => `Step ${n}`,
    stepDone: 'done',
    doneShort: 'Done',
    installTitle: (app: string) => `Install ${app}`,
    addTitle: 'Add subscription',
    usageTitle: 'Turn on VPN',
    alreadyInstalled: 'Already installed — next',
    installedNext: 'Installed — next',
    addSubscription: 'Add subscription',
    tryAgain: 'Try again',
    notAdded: 'Subscription did not appear?',
    noticeInstalled: 'App installed',
    notInstalled: 'Not yet',
    noticeAdded: 'Subscription added',
    notAddedShort: 'Not there?',
    noOpenLead: (app: string) => `${app} did not open?`,
    noOpenTip: 'The app may not be installed yet. Video and manual setup —',
    connected: 'VPN is on',
    markedDone: 'Done',
    more: 'More',
    less: 'Less',

    helpTitle: 'Something went wrong?',
    helpFallbackTitle: 'If the subscription was not added',
    helpHowTo: 'How to add the subscription',
    copyLink: 'Copy subscription link',
    copyLinkHint: 'Add manually',
    copied: 'Copied',
    support: 'Contact support',

    change: 'Change',
    pickerTitle: 'Which device do you use?',
    pickerApp: 'App',
    recommended: 'Recommended',
    pickerDone: 'Done',
    close: 'Close',

    finaleTitle: 'Done! VPN is connected 🎉',
    finaleTitleShort: 'Done! 🎉',
    finaleText: (brand: string, app: string) =>
      `${brand ? `The ${brand} subscription is` : 'The subscription is'} in ${app}. Use the big button in the app to turn VPN on and off.`,
    anotherDevice: 'Connect another device',
    showSteps: 'Show steps',
    toHome: 'Home',

    illAdd: '+ Subscription',
    illAdded: 'subscription added',
    illOff: 'Off',
    illOn: 'Connected',
  },
}

export type GuideText = (typeof guideText)['ru']
